name: Bandit Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit (generate report)
        run: |
          # Genera el reporte en texto; no detener el job si hay issues
          bandit -r . -f txt -o bandit-report.txt || true
          # Mostrar por logs (opcional, útil para ver resultados en la UI)
          echo "========== BANDIT REPORT BEGIN =========="
          cat bandit-report.txt || true
          echo "=========== BANDIT REPORT END ==========="

      - name: Upload Bandit Report
        if: always()                    # fuerza la subida aunque algún paso previo falle
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.txt
